### ISSUE TITLE
Immediately Fails

### ISSUE THREAD

**Issue by mchughs** [metasoarous/oz#132]
On a brand-new, empty lein project  `(oz/start-server!)` opens the browsers and displays a stack trace. 

project.clj
```clojure
(defproject foobar "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [metasoarous/oz "1.6.0-alpha26"]]
  :repl-options {:init-ns foobar.core})
```

foobar/core.cljs
```clojure
(ns foobar.core
  (:require [oz.core :as oz]))

(oz/start-server!)
```

Trace at localhost:10666 after running `lein repl` from the project directory.
```txt
java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
	at ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)
	at ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)
	at ring.middleware.cookies$write_cookies$iter__1354__1358$fn__1359.invoke(cookies.clj:92)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)
	at ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)
	at ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)
	at ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.middleware.session$session_response.invokeStatic(session.clj:70)
	at ring.middleware.session$session_response.doInvoke(session.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at ring.middleware.session$wrap_session$fn__1527.invoke(session.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__1567.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__1633.invoke(nested_params.clj:84)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__1900.invoke(multipart_params.clj:117)
	at ring.middleware.params$wrap_params$fn__1932.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__1394.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2125.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__1976.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__2074.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__2097.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__2034.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.cljsjs$wrap_cljsjs$fn__2279.invoke(cljsjs.clj:50)
	at ring.middleware.gzip$wrap_gzip$fn__2241.invoke(gzip.clj:100)
	at clojure.lang.Var.invoke(Var.java:384)
	at aleph.http.server$handle_request$fn__23901$f__18145__auto____23902.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__18027$f__18028.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metasoarous** [comment]
Hi @mchughs. Thanks for reporting.

This looks to be the same issue as #125, which should be fixed now via 9e78fc0. See if bumping versions to `[metasoarous/oz "1.6.0-alpha27"]` solves this issue for you.

Alternatively, this problem seems to be specific to the dependency resolution of Leiningen; The `clj`/`deps.edn` tooling does not have this problem. It's what I tend to use to test things, and so is more likely to work without issue; No time like the present to switch :-)

Thanks again!

**Comment by mchughs** [comment]
Bumping versions to alpha27 did not resolve the issue for me. But forcing an upgrade on the version of ring through an explicitly dependency did fix the issue.

I can look into submitting a PR so that people don't run into this issue again when using lein.

**Comment by metasoarous** [comment]
Thanks for the update @mchughs 

This is rather confusing. I just released `alpha27` after bumping `ring` to `1.8.1`, so not sure how it could still be failing.

Would you please try running `lein clean` to make sure there isn't a stale build artifact muddying the waters? After that please try `alpha28`.

Would greatly appreciate a PR if neither of those steps help, and you're able to resolve the problem.

Thanks again

**Comment by zackteo** [comment]
Am encountering this too with lein (with CIDER). As mentioned, adding 
```
[ring/ring-core "1.8.1"]
```
works for now :)

**Comment by mchughs** [comment]
I checked the lein deps :tree on a lein project.clj containing only a dependency to alpha28 (throws ring related error) and I compared that to the lein deps :tree of the project containing a depency of alpha28 and ring/ring-core "1.8.1" (doesn't throw the error).

The differences of the two trees are few but most striking is that the without the explicit inclusion of ring-core 1.8.1 we actually get ring-core 1.4.0

```clojure
;; Without explicit dependency in project.clj
;; lein deps :why ring/ring-core
 [metasoarous/oz 1.6.0-alpha28]
   [ring-cljsjs 0.1.0]
     [ring/ring-core 1.4.0]
```

I see in your deps.edn you have the line `ring {:mvn/version "1.8.1"}` so I tried being more explicit, checked out the oz project, and I added `ring/ring-core {:mvn/version "1.8.1"}` to the deps.edn.

I then tried building a jar using your `make build` and requiring this jar as a local repo in my project via the method described [here](https://stackoverflow.com/a/9917149). Lein deps seemed to treat this locally defined jar file as a black box so I couldn't compare it. It also seemed like it wasn't pulling in dependencies properly so I may not have carried out the steps properly.

All that being said, If you want to try to explicitly add `ring/ring-core {:mvn/version "1.8.1"}` to the deps.edn, that may fix the problem but I was unable to verify it.

**Comment by metasoarous** [comment]
Thanks for the confirmation @zackteo, and @mchughs for the additional investigation here.

This seems to explain what's going on. Specifying a particular `ring` version in _my_ `deps.edn` isn't doing the trick, because it's really the `ring-core` dependency that's the issue, and this ends up being at the same level removed in the tree from `ring` vs `ring-cljsjs`. This is different if _you_ add `ring`, because then it's a shorter path from `ring` to `ring-core` than from `oz` to `ring-cljsjs` to `ring-core`. Interestingly, it may actually be chance in this case that `clj` is getting it right over `lein`.

In any case, we're not even using `ring-cljsjs` any longer, so I've removed that dependency and released `1.6.0-alpha29`. Please give that a shot and let me know how it goes (and reopen this issue if the issue persists).

Thanks again!

**Comment by mchughs** [comment]
Works for me now on `1.6.0-alpha30`. nicely done

**Comment by metasoarous** [comment]
Wonderful! Thanks for the update. Glad we have that resolved.
